---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
env:
  - PUPPET_VERSION="~> 4.2.1" STRICT_VARIABLES="yes"
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
